### ISSUE TITLE
Highscores

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/ColorPhun#1]
Provide high score persistence via SQLite.

**Comment by SwapnilDarode** [comment]
In progress

**Comment by prakhar1989** [comment]
- User provides name
- Persist last 5 top scores (with date)

@mdzafar Any other inputs?

**Comment by prakhar1989** [comment]
Minor change
1. We prompt last name specified
2. Persist only top 5 scores (last doesn't make sense in this context)

**Comment by prakhar1989** [comment]
Moving user name prompt to separate issue. Closing issue as feature completed.
