### ISSUE TITLE
Generate "better" colors

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/ColorPhun#12]
Find a way to programmatically generate "better" colors.

**Comment by prakhar1989** [comment]
[This](https://github.com/prakhar1989/ColorPhun/blob/master/app/src/main/java/com/example/prakharsriv/colorphun/MainActivity.java#L186-L200) is the part where a set of new random colors are generated. Just replace the random generation by a better algorithm.

**Comment by shashankgroovy** [comment]
Roger that! I reckon I saw a post a on HN regarding generating colors programmatically. Do let me know if you come across it.

**Comment by prakhar1989** [comment]
Found a relevant SO post to do that - http://stackoverflow.com/questions/43044/algorithm-to-randomly-generate-an-aesthetically-pleasing-color-palette. Play with the formula and see if you can get better colors.

**Comment by prakhar1989** [comment]
Also relevant - http://www.checkman.io/please/ and http://llllll.li/randomColor/
